# Generated by Django 3.2 on 2021-07-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_paper_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='paper',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
