# Generated by Django 3.2 on 2021-07-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('app', '0003_auto_20210718_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='email',
        ),
        migrations.AddField(
            model_name='paper',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.authors'),
        ),
    ]
